spring:
  application:
    name: bank-simulator
  jpa:
    database: H2
  datasource:
    url: jdbc:h2:mem:banksimulatordb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  liquibase:
    change-log: db/changelog/db.changelog-root.yml
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8080